"""
Django settings for onlineretailpos project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

# Take environment variables from .env file
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", bool)

ALLOWED_HOSTS = env("ALLOWED_HOSTS", list)

DEFAULT_CHARSET = "utf-8"


# Application definition
INSTALLED_APPS = [
    # "admin_interface", #Interface if Admin Port Customization is needed
    "colorfield",
    "onlineretailpos.admin.MyAdminConfig",  #'django.contrib.admin',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "jquery",
    "mathfilters",
    "import_export",
    "rangefilter",
    "django_admin_logs",
    "apps.core",
    "apps.inventory",
    "apps.transaction",
    "apps.cart",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "onlineretailpos.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "onlineretailpos.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": env("DB_ENGINE"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
        "NAME": env("DB_NAME"),
        "USER": env("DB_USERNAME"),
        "PASSWORD": env("DB_PASSWORD"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [BASE_DIR / "static"]

STORAGES = {
    "default": {
        "BACKEND": env(
            "DEFAULT_FILE_STORAGE",
            default="django.core.files.storage.FileSystemStorage",
        ),
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "media/"


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "core.User"


CART_SESSION_ID = "cart"

PROJECT_DIR = os.path.join(BASE_DIR, "onlineretailpos")

X_FRAME_OPTIONS = "SAMEORIGIN"

SILENCED_SYSTEM_CHECKS = ["security.W019"]


# HTTPS Security - Django
SESSION_COOKIE_SECURE = env("SESSION_COOKIE_SECURE", bool)

CSRF_COOKIE_SECURE = env("CSRF_COOKIE_SECURE", bool)

SECURE_SSL_REDIRECT = env("SECURE_SSL_REDIRECT", bool)

# HSTS Security - Django
SECURE_HSTS_SECONDS = env("SECURE_HSTS_SECONDS", cast=int)

SECURE_HSTS_PRELOAD = env("SECURE_HSTS_PRELOAD", bool)

SECURE_HSTS_INCLUDE_SUBDOMAINS = env("SECURE_HSTS_INCLUDE_SUBDOMAINS", bool)


# Store Information
# For Line Break add \n
# Can not be more than (RECEIPT_CHAR_COUNT - 2) Characters per line(\n), if wants to add more break it up by \n new line
RECEIPT_CHAR_COUNT = env("RECEIPT_CHAR_COUNT", int)

STORE_NAME = env("STORE_NAME")  # Can not be more than RECEIPT_CHAR_COUNT

STORE_ADDRESS = env("STORE_ADDRESS")

STORE_PHONE = env("STORE_PHONE")

INCLUDE_PHONE_IN_HEADING = env("INCLUDE_PHONE_IN_HEADING", bool)

RECEIPT_HEAD = f"{STORE_NAME}\n{STORE_ADDRESS}"

RECEIPT_HEAD = (
    RECEIPT_HEAD + f"\n{STORE_PHONE}" if INCLUDE_PHONE_IN_HEADING else RECEIPT_HEAD
)
RECEIPT_ADDITIONAL_HEADING = env("RECEIPT_ADDITIONAL_HEADING", default=None)
RECEIPT_HEADER = (
    f"{RECEIPT_HEAD}\n{RECEIPT_ADDITIONAL_HEADING}"
    if RECEIPT_ADDITIONAL_HEADING
    else RECEIPT_HEAD
)
RECEIPT_FOOTER = env("RECEIPT_FOOTER")


# Printer Settings
PRINTER_VENDOR_ID = env("PRINTER_VENDOR_ID")

PRINTER_PRODUCT_ID = env("PRINTER_PRODUCT_ID")

PRINT_RECEIPT = env("PRINT_RECEIPT", bool)

CASH_DRAWER = env("CASH_DRAWER", bool)

DEFAULT_CURRENCY_CODE = env("DEFAULT_CURRENCY_CODE", default="USD")

DEFAULT_CURRENCY_SYMBOL = env("DEFAULT_CURRENCY_SYMBOL", default="$")
